version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - '5678:5678'
    volumes:
      - /var/images/n8n:/home/node/.n8n
    environment:

      - N8N_SECURE_COOKIE=false 
